### ISSUE TITLE
Datenbankupdate-Log farbig darstellen

### ISSUE THREAD

**Issue by ubruhin** [sandboxgangster/Part-DB#27]
Zitat von https://www.mikrocontroller.net/topic/305023#3343649:
> Bei DB update bin ich etwas erschrocken als lauter rote SQL Zeilen 
ausgegeben wurden. Könnte man nur Fehler rot ausgeben und den Rest 
schwarz?

Wäre auf jeden Fall sinnvoll :-)

**Comment by susnux** [comment]
Hier wäre schwarz oder blau vielleicht für "erfolgreich" die richtige Farbe, man denke an Menschen mit Rot-Grün-Sehschwäche. So als Anmerkung.
